### ISSUE TITLE
import RSA alway null

### ISSUE THREAD

**Issue by xuantungmta** [amitaymolko/react-native-rsa-native#76]
I use sameple code 
```
import { RSA } from 'react-native-rsa-native';
 
let message = "my secret message";
 
RSA.generateKeys(4096) // set key size
.then(keys => {
    console.log('4096 private:', keys.private); // the private key
    console.log('4096 public:', keys.public); // the public key
    RSA.encrypt(message, keys.public)
    .then(encodedMessage => {
        console.log(`the encoded message is ${encodedMessage}`);
        RSA.decrypt(encodedMessage, keys.private)
        .then(decryptedMessage => {
            console.log(`The original message was ${decryptedMessage}`);
        });
    });
});
```
but RSA alway null

**Comment by amitaymolko** [comment]
if on iOS remember to run pod install.
Also we just released v2.0.0 give it a try

**Comment by ralucaBoyte** [comment]
And what about Android? I tried v2.0.2 and v1.1.4 and still getting this error.

**Comment by luis-antonio-dev** [comment]
Im using the version v2.0.5 and still getting error
